# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cWj0OQtobLWNr_a0KIziRZUssplBWuZG
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

from scipy.integrate import solve_ivp

sns.set_theme(style="whitegrid")


def seir_forward(t_array, y0, N, beta, alpha, delta, gamma):

    def func(t, y):
        S, E, I, R = y
        dS_dt = (- beta * S / N * I)
        dE_dt = (beta * S / N * I) + (gamma*R) - (alpha*E)
        dI_dt = (alpha*E) - (delta*I)
        dR_dt = (delta*I) - (gamma*R)
        return np.array([dS_dt, dE_dt, dI_dt, dR_dt])

    t_span = (t_array[0], t_array[-1])
    sol = solve_ivp(func, t_span, y0, t_eval=t_array)
    return sol.y.T


st.set_page_config(
     page_title="Stage 1: SEIR Model",
     page_icon="🧬",
     layout="wide",
)

st.title("Stage 1 SEIR Model")

tab_seir, tab_help = st.tabs(["SEIR", "Help"])

with tab_seir:

    st.latex(r"""
        \begin{align*}
        \frac{dS}{dt} &= - \frac{\beta}{N}  S I \\
        \frac{dE}{dt} &= \frac{\beta}{N} S I + \gamma  R - \alpha E \\
        \frac{dI}{dt} &= \alpha E -\delta I \\
        \frac{dR}{dt} &= \delta I - \gamma R \\
        \end{align*}
    """
    )

    col11, col12, col13, col14, col15, col16 = st.columns(6)

    N = col11.number_input(
        "N",
        min_value=100,
        max_value=10000,
        value=1000,
        step=100,
        format=None,
        help="Population",
    )

    n_days = col12.number_input(
        "Number of days",
        min_value=30,
        max_value=366,
        value=60,
        step=1,
        format=None,
        help="Number of days for simulation",
    )

    beta = col13.number_input(
        "Beta",
        min_value=0.001,
        max_value=1.0,
        value=0.5,
        step=0.001,
        format=None,
        help="Rate at which high school population becomes exposed to stress/anxiety",
    )

    gamma = col16.number_input(
        "Gamma",
        min_value=0.001,
        max_value=1.0,
        value=1 / 14,
        step=0.001,
        format=None,
        help="Rate at which recovered population become re-exposed to stress/anxiety",
    )


    alpha = col14.number_input(
        "Mu",
        min_value=0.001,
        max_value=1.0,
        value=1 / 5,
        step=0.001,
        format=None,
        help="Rate at which population becomes infected with stress/anxiety",
    )

    delta = col15.number_input(
        "Mu",
        min_value=0.001,
        max_value=1.0,
        value=1 / 5,
        step=0.001,
        format=None,
        help="Rate at which infected population recovers from stress/anxiety",
    )


    if st.button("Run forward simulation"):
        with st.spinner('Wait for it...'):
            # Initial conditions
            t_train = np.arange(0, n_days, 1)
            parameters = {
                "beta": beta,
                "gamma": gamma,
                "delta": delta,
                "alpha" : alpha,
            }
            S_0 = N - 1
            E_0 = 1
            I_0 = 0
            R_0 = 0
            y0 = [S_0, E_0, I_0, R_0]
            y_sol = seir_forward(t_train, y0, N, beta, alpha, delta, gamma)

            # Create dataframe
            model_name = "SEIR"
            populations_names = list(model_name)
            data_real = (
                    pd.DataFrame(y_sol, columns=populations_names)
                    .assign(time=t_train)
                    .melt(id_vars="time", var_name="status", value_name="population")
            )

            # Plot
            fig, ax = plt.subplots(figsize=(10, 4))
            sns.lineplot(
                data=data_real,
                x="time",
                y="population",
                hue="status",
                legend=True,
                linestyle="dashed",
                ax=ax
            )
            ax.set_title(f"{model_name} model - Forward Simulation")
            st.pyplot(fig)


with tab_help:
    url = "https://raw.githubusercontent.com/aoguedao/neural-computing-book/main/images/coyoya.jpg"
    st.header("Work in progress... Here is a kitty.")
    st.image(url, width=200)

